[package]
name = "diacritics"
version = "0.1.0"
authors = ["yesseri <henrik.zenkert@gmail.com>"]
edition = "2018"
license = "GNU GPLv3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
